python train_ebm_cifar10_gan_r3gan_ctrl_vit_dec_imagenet.py \
    --data_path /root/autodl-tmp/imagenet100/train/ \
    --output_dir /root/autodl-tmp/output/imagenet100_ctrl \
    --img_size 128 \
    --patch_size 16 \
    --epochs 1200 \
    --batch_size 128 \
    --embed_dim 192 \
    --decoder_embed_dim 192 \
    --encoder_depth 12 \
    --decoder_depth 4 \
    --num_heads 3 
